// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.CodeCategory;
import com.terram.CodeCategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CodeCategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CodeCategoryDataOnDemand: @Component;
    
    private Random CodeCategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<CodeCategory> CodeCategoryDataOnDemand.data;
    
    public CodeCategory CodeCategoryDataOnDemand.getNewTransientCodeCategory(int index) {
        CodeCategory obj = new CodeCategory();
        return obj;
    }
    
    public CodeCategory CodeCategoryDataOnDemand.getSpecificCodeCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CodeCategory obj = data.get(index);
        Long id = obj.getId();
        return CodeCategory.findCodeCategory(id);
    }
    
    public CodeCategory CodeCategoryDataOnDemand.getRandomCodeCategory() {
        init();
        CodeCategory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CodeCategory.findCodeCategory(id);
    }
    
    public boolean CodeCategoryDataOnDemand.modifyCodeCategory(CodeCategory obj) {
        return false;
    }
    
    public void CodeCategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CodeCategory.findCodeCategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CodeCategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CodeCategory>();
        for (int i = 0; i < 10; i++) {
            CodeCategory obj = getNewTransientCodeCategory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
