// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.Code;
import com.terram.CodeDataOnDemand;
import com.terram.CodeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CodeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CodeIntegrationTest: @Transactional;
    
    @Autowired
    private CodeDataOnDemand CodeIntegrationTest.dod;
    
    @Test
    public void CodeIntegrationTest.testCountCodes() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        long count = Code.countCodes();
        Assert.assertTrue("Counter for 'Code' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CodeIntegrationTest.testFindCode() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = Code.findCode(id);
        Assert.assertNotNull("Find method for 'Code' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Code' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CodeIntegrationTest.testFindAllCodes() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        long count = Code.countCodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Code', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Code> result = Code.findAllCodes();
        Assert.assertNotNull("Find all method for 'Code' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Code' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CodeIntegrationTest.testFindCodeEntries() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        long count = Code.countCodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Code> result = Code.findCodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Code' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Code' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CodeIntegrationTest.testFlush() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = Code.findCode(id);
        Assert.assertNotNull("Find method for 'Code' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Code' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CodeIntegrationTest.testMergeUpdate() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = Code.findCode(id);
        boolean modified =  dod.modifyCode(obj);
        Integer currentVersion = obj.getVersion();
        Code merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Code' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", dod.getRandomCode());
        Code obj = dod.getNewTransientCode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Code' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Code' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Code' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CodeIntegrationTest.testRemove() {
        Code obj = dod.getRandomCode();
        Assert.assertNotNull("Data on demand for 'Code' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Code' failed to provide an identifier", id);
        obj = Code.findCode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Code' with identifier '" + id + "'", Code.findCode(id));
    }
    
}
