// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.CodeCategory;
import com.terram.CodeCategoryDataOnDemand;
import com.terram.CodeCategoryIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CodeCategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CodeCategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CodeCategoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CodeCategoryIntegrationTest: @Transactional;
    
    @Autowired
    private CodeCategoryDataOnDemand CodeCategoryIntegrationTest.dod;
    
    @Test
    public void CodeCategoryIntegrationTest.testCountCodeCategorys() {
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", dod.getRandomCodeCategory());
        long count = CodeCategory.countCodeCategorys();
        Assert.assertTrue("Counter for 'CodeCategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testFindCodeCategory() {
        CodeCategory obj = dod.getRandomCodeCategory();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to provide an identifier", id);
        obj = CodeCategory.findCodeCategory(id);
        Assert.assertNotNull("Find method for 'CodeCategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CodeCategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testFindAllCodeCategorys() {
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", dod.getRandomCodeCategory());
        long count = CodeCategory.countCodeCategorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'CodeCategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CodeCategory> result = CodeCategory.findAllCodeCategorys();
        Assert.assertNotNull("Find all method for 'CodeCategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CodeCategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testFindCodeCategoryEntries() {
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", dod.getRandomCodeCategory());
        long count = CodeCategory.countCodeCategorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CodeCategory> result = CodeCategory.findCodeCategoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CodeCategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CodeCategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testFlush() {
        CodeCategory obj = dod.getRandomCodeCategory();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to provide an identifier", id);
        obj = CodeCategory.findCodeCategory(id);
        Assert.assertNotNull("Find method for 'CodeCategory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCodeCategory(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CodeCategory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testMergeUpdate() {
        CodeCategory obj = dod.getRandomCodeCategory();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to provide an identifier", id);
        obj = CodeCategory.findCodeCategory(id);
        boolean modified =  dod.modifyCodeCategory(obj);
        Integer currentVersion = obj.getVersion();
        CodeCategory merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CodeCategory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", dod.getRandomCodeCategory());
        CodeCategory obj = dod.getNewTransientCodeCategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CodeCategory' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CodeCategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CodeCategoryIntegrationTest.testRemove() {
        CodeCategory obj = dod.getRandomCodeCategory();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CodeCategory' failed to provide an identifier", id);
        obj = CodeCategory.findCodeCategory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CodeCategory' with identifier '" + id + "'", CodeCategory.findCodeCategory(id));
    }
    
}
