// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.SessionToken;
import com.terram.SessionTokenDataOnDemand;
import com.terram.SessionTokenIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SessionTokenIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SessionTokenIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SessionTokenIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SessionTokenIntegrationTest: @Transactional;
    
    @Autowired
    private SessionTokenDataOnDemand SessionTokenIntegrationTest.dod;
    
    @Test
    public void SessionTokenIntegrationTest.testCountSessionTokens() {
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", dod.getRandomSessionToken());
        long count = SessionToken.countSessionTokens();
        Assert.assertTrue("Counter for 'SessionToken' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SessionTokenIntegrationTest.testFindSessionToken() {
        SessionToken obj = dod.getRandomSessionToken();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to provide an identifier", id);
        obj = SessionToken.findSessionToken(id);
        Assert.assertNotNull("Find method for 'SessionToken' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SessionToken' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SessionTokenIntegrationTest.testFindAllSessionTokens() {
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", dod.getRandomSessionToken());
        long count = SessionToken.countSessionTokens();
        Assert.assertTrue("Too expensive to perform a find all test for 'SessionToken', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SessionToken> result = SessionToken.findAllSessionTokens();
        Assert.assertNotNull("Find all method for 'SessionToken' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SessionToken' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SessionTokenIntegrationTest.testFindSessionTokenEntries() {
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", dod.getRandomSessionToken());
        long count = SessionToken.countSessionTokens();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SessionToken> result = SessionToken.findSessionTokenEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SessionToken' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SessionToken' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SessionTokenIntegrationTest.testFlush() {
        SessionToken obj = dod.getRandomSessionToken();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to provide an identifier", id);
        obj = SessionToken.findSessionToken(id);
        Assert.assertNotNull("Find method for 'SessionToken' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySessionToken(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SessionToken' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SessionTokenIntegrationTest.testMergeUpdate() {
        SessionToken obj = dod.getRandomSessionToken();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to provide an identifier", id);
        obj = SessionToken.findSessionToken(id);
        boolean modified =  dod.modifySessionToken(obj);
        Integer currentVersion = obj.getVersion();
        SessionToken merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SessionToken' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SessionTokenIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", dod.getRandomSessionToken());
        SessionToken obj = dod.getNewTransientSessionToken(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SessionToken' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SessionToken' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SessionTokenIntegrationTest.testRemove() {
        SessionToken obj = dod.getRandomSessionToken();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SessionToken' failed to provide an identifier", id);
        obj = SessionToken.findSessionToken(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SessionToken' with identifier '" + id + "'", SessionToken.findSessionToken(id));
    }
    
}
