// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.SessionToken;
import com.terram.SessionTokenDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SessionTokenDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SessionTokenDataOnDemand: @Component;
    
    private Random SessionTokenDataOnDemand.rnd = new SecureRandom();
    
    private List<SessionToken> SessionTokenDataOnDemand.data;
    
    public SessionToken SessionTokenDataOnDemand.getNewTransientSessionToken(int index) {
        SessionToken obj = new SessionToken();
        return obj;
    }
    
    public SessionToken SessionTokenDataOnDemand.getSpecificSessionToken(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SessionToken obj = data.get(index);
        Long id = obj.getId();
        return SessionToken.findSessionToken(id);
    }
    
    public SessionToken SessionTokenDataOnDemand.getRandomSessionToken() {
        init();
        SessionToken obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SessionToken.findSessionToken(id);
    }
    
    public boolean SessionTokenDataOnDemand.modifySessionToken(SessionToken obj) {
        return false;
    }
    
    public void SessionTokenDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SessionToken.findSessionTokenEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SessionToken' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SessionToken>();
        for (int i = 0; i < 10; i++) {
            SessionToken obj = getNewTransientSessionToken(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
