// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.UsersPrincipal;
import com.terram.UsersPrincipalDataOnDemand;
import com.terram.UsersPrincipalIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsersPrincipalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsersPrincipalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsersPrincipalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UsersPrincipalIntegrationTest: @Transactional;
    
    @Autowired
    private UsersPrincipalDataOnDemand UsersPrincipalIntegrationTest.dod;
    
    @Test
    public void UsersPrincipalIntegrationTest.testCountUsersPrincipals() {
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", dod.getRandomUsersPrincipal());
        long count = UsersPrincipal.countUsersPrincipals();
        Assert.assertTrue("Counter for 'UsersPrincipal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testFindUsersPrincipal() {
        UsersPrincipal obj = dod.getRandomUsersPrincipal();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to provide an identifier", id);
        obj = UsersPrincipal.findUsersPrincipal(id);
        Assert.assertNotNull("Find method for 'UsersPrincipal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UsersPrincipal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testFindAllUsersPrincipals() {
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", dod.getRandomUsersPrincipal());
        long count = UsersPrincipal.countUsersPrincipals();
        Assert.assertTrue("Too expensive to perform a find all test for 'UsersPrincipal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UsersPrincipal> result = UsersPrincipal.findAllUsersPrincipals();
        Assert.assertNotNull("Find all method for 'UsersPrincipal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UsersPrincipal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testFindUsersPrincipalEntries() {
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", dod.getRandomUsersPrincipal());
        long count = UsersPrincipal.countUsersPrincipals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UsersPrincipal> result = UsersPrincipal.findUsersPrincipalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UsersPrincipal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UsersPrincipal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testFlush() {
        UsersPrincipal obj = dod.getRandomUsersPrincipal();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to provide an identifier", id);
        obj = UsersPrincipal.findUsersPrincipal(id);
        Assert.assertNotNull("Find method for 'UsersPrincipal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsersPrincipal(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UsersPrincipal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testMergeUpdate() {
        UsersPrincipal obj = dod.getRandomUsersPrincipal();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to provide an identifier", id);
        obj = UsersPrincipal.findUsersPrincipal(id);
        boolean modified =  dod.modifyUsersPrincipal(obj);
        Integer currentVersion = obj.getVersion();
        UsersPrincipal merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UsersPrincipal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", dod.getRandomUsersPrincipal());
        UsersPrincipal obj = dod.getNewTransientUsersPrincipal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UsersPrincipal' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UsersPrincipal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsersPrincipalIntegrationTest.testRemove() {
        UsersPrincipal obj = dod.getRandomUsersPrincipal();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersPrincipal' failed to provide an identifier", id);
        obj = UsersPrincipal.findUsersPrincipal(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UsersPrincipal' with identifier '" + id + "'", UsersPrincipal.findUsersPrincipal(id));
    }
    
}
