// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.UsersCalendar;
import com.terram.UsersCalendarDataOnDemand;
import com.terram.UsersCalendarIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsersCalendarIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsersCalendarIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsersCalendarIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UsersCalendarIntegrationTest: @Transactional;
    
    @Autowired
    private UsersCalendarDataOnDemand UsersCalendarIntegrationTest.dod;
    
    @Test
    public void UsersCalendarIntegrationTest.testCountUsersCalendars() {
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", dod.getRandomUsersCalendar());
        long count = UsersCalendar.countUsersCalendars();
        Assert.assertTrue("Counter for 'UsersCalendar' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testFindUsersCalendar() {
        UsersCalendar obj = dod.getRandomUsersCalendar();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to provide an identifier", id);
        obj = UsersCalendar.findUsersCalendar(id);
        Assert.assertNotNull("Find method for 'UsersCalendar' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UsersCalendar' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testFindAllUsersCalendars() {
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", dod.getRandomUsersCalendar());
        long count = UsersCalendar.countUsersCalendars();
        Assert.assertTrue("Too expensive to perform a find all test for 'UsersCalendar', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UsersCalendar> result = UsersCalendar.findAllUsersCalendars();
        Assert.assertNotNull("Find all method for 'UsersCalendar' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UsersCalendar' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testFindUsersCalendarEntries() {
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", dod.getRandomUsersCalendar());
        long count = UsersCalendar.countUsersCalendars();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UsersCalendar> result = UsersCalendar.findUsersCalendarEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UsersCalendar' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UsersCalendar' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testFlush() {
        UsersCalendar obj = dod.getRandomUsersCalendar();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to provide an identifier", id);
        obj = UsersCalendar.findUsersCalendar(id);
        Assert.assertNotNull("Find method for 'UsersCalendar' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsersCalendar(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UsersCalendar' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testMergeUpdate() {
        UsersCalendar obj = dod.getRandomUsersCalendar();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to provide an identifier", id);
        obj = UsersCalendar.findUsersCalendar(id);
        boolean modified =  dod.modifyUsersCalendar(obj);
        Integer currentVersion = obj.getVersion();
        UsersCalendar merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UsersCalendar' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", dod.getRandomUsersCalendar());
        UsersCalendar obj = dod.getNewTransientUsersCalendar(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UsersCalendar' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UsersCalendar' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsersCalendarIntegrationTest.testRemove() {
        UsersCalendar obj = dod.getRandomUsersCalendar();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsersCalendar' failed to provide an identifier", id);
        obj = UsersCalendar.findUsersCalendar(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UsersCalendar' with identifier '" + id + "'", UsersCalendar.findUsersCalendar(id));
    }
    
}
