// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.UsersCalendar;
import com.terram.UsersCalendarDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UsersCalendarDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsersCalendarDataOnDemand: @Component;
    
    private Random UsersCalendarDataOnDemand.rnd = new SecureRandom();
    
    private List<UsersCalendar> UsersCalendarDataOnDemand.data;
    
    public UsersCalendar UsersCalendarDataOnDemand.getNewTransientUsersCalendar(int index) {
        UsersCalendar obj = new UsersCalendar();
        return obj;
    }
    
    public UsersCalendar UsersCalendarDataOnDemand.getSpecificUsersCalendar(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UsersCalendar obj = data.get(index);
        Long id = obj.getId();
        return UsersCalendar.findUsersCalendar(id);
    }
    
    public UsersCalendar UsersCalendarDataOnDemand.getRandomUsersCalendar() {
        init();
        UsersCalendar obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UsersCalendar.findUsersCalendar(id);
    }
    
    public boolean UsersCalendarDataOnDemand.modifyUsersCalendar(UsersCalendar obj) {
        return false;
    }
    
    public void UsersCalendarDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UsersCalendar.findUsersCalendarEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UsersCalendar' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UsersCalendar>();
        for (int i = 0; i < 10; i++) {
            UsersCalendar obj = getNewTransientUsersCalendar(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
